scripts/build_population_layouts.py

See #45 for problem description and reason behind the value difference:
"The difference arises due to the input dataset. In PyPSA-Eur-Sec "nuts3_shapes.geojson" is used to get population data, the value of population is given in thousands. In PyPSA-Earth-Sec we use GADM shapes, which have the value in real numbers
https://github.com/PyPSA/pypsa-eur-sec/blob/b6cfcf6364e1037ce2bdad53504c8df7eb2b72b0/scripts/build_population_layouts.py#L22"
This PR sets the value to thousands to avoid future issues with the population values in other scripts.  Closes #45

 Set value of population to thousands

---

Snakefile

We inherited the config input from pypsa-eur, but does it make sense? I haven't seen it used anywhere even in pypsa-eur-sec
The script works fine also without it

Reove config option from solve_network

---

Snakefile
config.pypsa-earth.yaml
config.yaml
data/industrial_production_per_country.csv
scripts/build_industrial_production_tomorrow.py
test/config.test1.yaml

The file `industrial_production_per_country.csv` was in the resource folder and hence not tracked, now it's in the data folder and the snakefile links are adjusted.

Include missing industry demand csv

---

config.yaml
scripts/prepare_sector_network.py

Changes the spatial representation depending on wether a network is enabled or not. 
E.g.  (“Africa gas” -> e.g. “spatial.gas.nodes”)

Enable spatial representation for biogas and biomass

---

.github/workflows/ci-linux.yaml
.github/workflows/ci-mac.yaml
.github/workflows/ci-windows.yaml
Snakefile
config.yaml
test/config.test1.yaml

This PR aims at fixing the references from pypsa-africa to pypsa-earth and re-enable the CI

Adapt to renamed repo and fix ci

---

.github/workflows/ci-linux.yaml
.github/workflows/ci-mac.yaml
.github/workflows/ci-windows.yaml

Fix the CI which currently tries to clone from "Africa", now changed to "Earth"..

fix: change CI clone from africa to earth

---

.gitignore
Snakefile
config.default.yaml
config.pypsa-earth.yaml

This PR distributes a `config.default.yaml` and copies it to `config.yaml` for individual scenario setting. This way, we can keep a running default yaml but still make our own personal scenario explorations without changing major things.
Note: previously we had a very strict limit on RE potentials, which is now removed.

Include config default

---

scripts/add_export.py

The most northern and western point of a selected region is taken to get the coordinates for the h2 export bus, including a buffer of approx. 220 km.

Add export location

---

config.default.yaml
scripts/plot_network.py

Plot_network.py used to crash because of a missing technology color in the config file. The boundaries of the plot was hard set to Morocco. Both fixed now.

add missing color and make plot boundaries flexible

---

Snakefile
config.default.yaml
scripts/prepare_ports.py

Added global ports as a rule. 
The data are automatically downloaded throught the script from: https://msi.nga.mil/Publications/WPI as a .csv
Then the data is prepared by using only small, medium and large ports and dropping the rest. 
Fraction is based on port sizr for each country.

Add global ports airports

---

.github/workflows/ci-linux.yaml
.github/workflows/ci-mac.yaml
.github/workflows/ci-windows.yaml
.gitmodules
README.md
Snakefile
scripts/build_population_layouts.py

Revise pypsa-earth dependency with git submodules and revise atlite deprecation.
Major commands to reproduce this PR are:
`git submodule add {github url}` : adds the package at {github url} as a submodule within the current folder. Optionally commits/branches/... can be specified
Note that the version will fix the pypsa-earth version to the current commit.
To update the submodule version to the latest commit, the following command can be used followed by a commit&PR to the repo:
`git submodule update`
With the new version, it is recommended to clone the repo using
`git clone --recurse-submodules update {repo path}` to automatically clone the pypsa-earth-sec repo AND the pypsa-earth submodule. README has been updated accordingly.
If only `git clone update {repo path}` is used, hence …

Git submodules

---

Snakefile
scripts/build_industry_demand.py
scripts/plot_network.py
scripts/plot_summary.py
scripts/prepare_sector_network.py

- Alignment of prepare_sector network with 2-digit-id which is originally received in busmap of alternatively clustered network
- Prevention of dropping column which is necessary for industry demand calculation performed in line 86.
- Directory change for successful mock_snakemake execution when debugging plot_network and plot_summary scripts
- Removal of leading whitespace, which enables assignment of tech colors for balance summary plots

Adaptation to 2-digit GADM id, matrix alignment, mock_snakemake directory

---

.gitmodules
config.default.yaml
config.pypsa-earth.yaml
scripts/helpers.py
scripts/solve_network.py
test/config.test1.yaml

This PR includes the monthly matching constraint of hydrogen
Open Questions:
- Matching for export hydrogen only or export + local hydrogen? -> Just export hydrogen + local AC demand
- The current implementation of annual matching (RES >= H2_export + AC_local) forces the local electricity system to be green as well. This is probably not intended in the first place but we have to be aware of it / fix it
Testing phase:
- run 200H model without matching, annual matching, monthly matching

Include monthly matching of hydrogen

---

README.md
scripts/helpers.py
scripts/plot_network.py
scripts/plot_summary.py

The xticks in the `plot_summary` functions were not rotated. When plotting many scenarios with long names, they have overlapped. Here, a rotation of 45 degrees of the labels is introduced.
Also, the link width is increased to show hydrogen pipelines with low capacity.

Rotate xticks of summary plots

---

README.md
Snakefile
config.default.yaml
config.pypsa-earth.yaml
scripts/add_export.py
scripts/plot_network.py
test/config.test1.yaml

Despite tackling #156 (which has been tested successfully), this PR includes the option to add costs to the "dummy" export store.
This PR includes more options to configure the export store. System effects of different settings are currently investigated.

Include export store options

---

scripts/prepare_sector_network.py

See #204 for details.
This implementation makes #174 and #201 (alternative co2 constraint implementations) unnecessary.
Set the co2_emissions of the carrier `oil` to zero.

fix: Avoid double CO2 accounting

---

config.default.yaml
config.pypsa-earth.yaml
scripts/solve_network.py
test/config.test1.yaml

Organizes the way we implement different green hydrogen settings. 
Open questions to @hazemakhalek:
- Do we need a `reference_case` for the yearly matching?
- Should we include `re_country_load` in monthly matching?

Organize green h2

---

scripts/solve_network.py

fetch electrolysis efficiency from network

---

Snakefile
config.default.yaml
scripts/add_export.py
scripts/build_ship_profile.py
test/config.test1.yaml

Include simplified shipping export profile.
Remaining things to do:

Include simplified shipping export profile

---

scripts/prepare_sector_network.py

This PR fixes a few bugs that occurred in counting the emissions. Main sectors affected are "industry" (oil and coal) as well as the custom sectors "services" and "residential"

Fix emission bugs

---

config.default.yaml
scripts/prepare_sector_network.py
test/config.test1.yaml

Add part load option for Fischer-Tropsch. Previously, there was no part load constraint for Fischer-Tropsch, which is introduced here and adjustable in the config. The implementation is similar to:
https://github.com/PyPSA/pypsa-eur/blob/f35ecbe4a01f220210c3a295ca93d805f5633824/scripts/prepare_sector_network.py#L2722-L2724

Add Fischer-Tropsch part load

---

scripts/prepare_sector_network.py

Fix `capital_cost` of Fischer-Tropsch. Since the `investment` parameter of technology data relates to `EUR/MW_FT` the efficiency is used to convert from EUR/MW_FT/a to EUR/MW_H2/a (https://github.com/PyPSA/technology-data/blob/8bb05d94ac603c463683b5ae12acf438fb962b4f/outputs/costs_2030.csv#L97).
This is is in line with `PyPSA-Eur`
https://github.com/PyPSA/pypsa-eur/blob/f35ecbe4a01f220210c3a295ca93d805f5633824/scripts/prepare_sector_network.py#L2718C9-L2719C68

Add Fischer-Tropsch efficiency in capital cost calculation

---

config.default.yaml
scripts/prepare_sector_network.py
test/config.test1.yaml

Provide the feature to set the land transport not depending on `planning_horizons` but on `Co2L` wildcard.
If turned on, then the BEV and FCEV shares are obtained depening on the "Co2L"-wildcard (e.g. "Co2L0.70: 0.10"). If "False", then the shares are obtained depending on the "demand" wildcard and "planning_horizons" wildcard as listed below (e.g. "DF_2050: 0.08")

Land transport shares depending on `Co2L`

---

scripts/prepare_ports.py

deleted storage options to fix HTTP 403 forbidden error

fix HTTP error 403: forbidden

---

config.default.yaml

fix: set enable to false to prevent keyerror "Co2L"

---

Snakefile
config.default.yaml
scripts/build_population_layouts.py
scripts/prepare_urban_percent.py
test/config.test1.yaml

- The data is collected from the United Nations CTAD: https://unctadstat.unctad.org/datacentre/
- Filtered for years after 2020.
- Saved in data/urban_percent.csv to be used normally in the workflow.
- New rule in Snakefile is also added.

Add prepare_urban_percent to the workflow

---

scripts/build_base_energy_totals.py
scripts/prepare_energy_totals.py

When no sector data is given for a country, we write nan values into base_energy_totals.csv instead of ignoring it.

fix: write nan values when sector data is not given

---

config.default.yaml
scripts/build_industry_demand.py
test/config.test1.yaml

Previsouly, an error occured if there is more than one year of production specified in `data/AL_production`. This PR solves the issue by providing the selection of a certain year in the config.

Fix aluminium production year

---

Snakefile
scripts/build_base_energy_totals.py

build_base_industry_totals.py
build_clustered_population_layouts.py
build_cop_profiles.py
build_heat_demand.py
build_industrial_database.py
build_industrial_distribution_key.py
copy_config.py
helpers.py
prepare_db.py …

Add Params to Rule build_base_energy_totals

---

Snakefile
scripts/build_cop_profiles.py

build_heat_demand.py
build_industrial_database.py
build_industrial_distribution_key.py
copy_config.py
helpers.py
prepare_db.py

Add Params to Rule build_cop_profiles

---

Snakefile
scripts/build_heat_demand.py

build_industrial_database.py
build_industrial_distribution_key.py
copy_config.py
helpers.py
prepare_db.py

Add Params to Rule build_heat_demand

---

Snakefile
scripts/build_industrial_distribution_key.py

copy_config.py
helpers.py
prepare_db.py

Add Params to build_industrial_distribution_key

---

Snakefile
scripts/build_ship_profile.py

copy_config.py
helpers.py
prepare_db.py

Add Params to build_ship_profile

---

Snakefile
scripts/build_solar_thermal_profiles.py

copy_config.py
helpers.py
prepare_db.py

Add Params build_solar_thermal_profiles

---

Snakefile
scripts/build_temperature_profiles.py

copy_config.py
helpers.py
prepare_db.py

Add Params to build_temperature_profiles

---

Snakefile
scripts/make_summary.py

Add Params make_summary

---

Snakefile
scripts/add_export.py

This PR is part of adding Params to all Rules in Snakemake under Issue #330 
build_base_energy_totals.py
build_base_industry_totals.py
build_clustered_population_layouts.py
build_cop_profiles.py
build_heat_demand.py
build_industrial_database.py
build_industrial_distribution_key.py
copy_config.py
helpers.py
prepare_db.py …

Add Params for Rule add_export.py

---

Snakefile
scripts/prepare_airports.py

Add Params to prepare_airports

---

Snakefile
scripts/prepare_db.py
scripts/prepare_energy_totals.py

Add Params to prepare_db and energy_totals

---

Snakefile
scripts/override_respot.py

Add to override_respot + panning_horizons wildcard

---

Snakefile
scripts/build_population_layouts.py

Add Params to build_population_layout

---

Snakefile
scripts/build_population_layouts.py

@energyLS  **PLEASE review this PR carefully. I added a wildcard for the urban_percentage year in Rule `build_population_layouts`  and therefore added `{planning_horizons}` wildcard to all Rules after that.**
copy_config.py
helpers.py
prepare_db.py …

Consider "urban_percentage" based on "panning_horizons" wildcard and its effect on all Rules

---

Snakefile
scripts/prepare_gas_network.py

fix MissingOutputException

---

scripts/prepare_sector_network.py

When modeling shipping and aviation excluding international bunker fuels, it was discovered that the corresponding emission columns in the loads dataframe contained NaN values. This issue arose from passing a pandas Series instead of a scalar when adding the load component, specifically in lines 1078 and 1408 of `prepare_sector_network.py`.
The multiplication of the p_set-value for residential and services gas emissions with the scalar 8760 had to be removed, as the value must correspond to the hourly emission load, as is set for every hour of the dynamic dataframe.

Fix emission bug

---

scripts/solve_network.py
test/config.test1.yaml
test/config.test_myopic.yaml

The proposed changes in the test configs intend to fix the infeasibility of the model.

Fix for test config
