pypsa-meets-earth/pypsa-earth-sec

Snakefile, config.yaml, data/airports.csv, data/ports.csv, scripts/helpers.py, scripts/prepare_sector_network.py
Features added to nodally disaggregate aviation and shipping data on the network.
=> Aviation and Shipping Nodal Disaggregation

.github/ISSUE_TEMPLATE/bug_request.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Closes #96 
As the title explains
=> Add templates for issues and pull requests

config.yaml, scripts/prepare_sector_network.py, scripts/solve_network.py
=> Add and test DAC

Snakefile, scripts/prepare_sector_network.py
Deletes file ref from snakefile which is not required anymore
=> Delete file ref which is not used in script

config.pypsa-earth.yaml, config.yaml, test/config.test1.yaml
1. The color key for "solid biomass for industry CC" is added, this was causing issues
2. The co2base value must be specified in `1.487e+8`, instead of `1.487e8`  (note; the'+' is required, otherwise snakemake interprets it as str not int)
=> Minor fixes

config.yaml, scripts/prepare_sector_network.py
The addition of Biomass and Biogas leads to infeasability. This PR aims to solve that and also issues that might appear with the new RES linker (see #140).
=> Include Biomass

scripts/make_summary.py, scripts/plot_summary.py
Some minor bugs in `make_summary` and `plot_summary` appeared after the merge, which are fixed in this PR and tested successfully.
=> Fix plot summary

config.pypsa-earth.yaml, scripts/prepare_sector_network.py
This PR cleans the main model script `prepare_sector_networks.py`
=> Clean prepare sector networks

scripts/build_industrial_distribution_key.py, scripts/build_industry_demand.py, scripts/prepare_heat_data.py, scripts/prepare_transport_data.py
This script is part of an effort to add a custom data feature to pypsa-earth-sec model.
The changes in the below scripts resolve:
1. The "NA" (Namibia) country code as NaN values read by read_csv function.
2. The custom data "Industry Machinery" dropped earlier in industry demand.
=> Added changes in scripts for NaN & custom data.

Snakefile, config.pypsa-earth.yaml
Update to the latest changes and fix CI.
For @energyLS , with this update the offshore wind issue should be fixed
=> Update to latest pypsa-earth main

Snakefile
Added copy commit rule + trigger it with every trigger of solve_network
=> feat: add copy commit rule

scripts/prepare_energy_totals.py
Simple fix to make the workflow flexible with more than one country analyzed at once
=> fix minor bug

scripts/plot_summary.py
Some labels were a bit off, e.g. using `hydrogen storage` for Electrolysis.
=> Rename plotting labels

scripts/build_industrial_database.py
ReadTimeoutError occured when accessing the Nominatim API (maybe due to bad internet connection). Country codes can be now retrieved my simple re-submission of request.
Ten re-tries were set as a threshold value.
- [x ] I tested my contribution locally and it seems to work fine.
=> Retries for Nominatim requests 

scripts/helpers.py
See explaination in #247.
"Peat" could be discussed on where to assign, I think coal makes sense.
=> Fix solid biomass for industry demand

scripts/build_base_energy_totals.py
=> bug: fixed round error in build_base_energy_total

config.default.yaml, config.pypsa-earth.yaml
=> Adding industry_util_factor to config.default

scripts/build_population_layouts.py
read_csv_nafix instead of pd.read_csv
=> fix Keyerror 'NA'

scripts/helpers.py, scripts/prepare_sector_network.py
implemented division through zero check
=> fix: ZeroDivision Error

config.pypsa-earth.yaml, scripts/prepare_gas_network.py
Updating the default commit of PyPSA-Earth submodule. Previous version used to cause problems when retrieving databundle as well as building cutout
=> Update PyPSA-Earth submodule

scripts/prepare_gas_network.py
=> fix TypeError

Snakefile, scripts/copy_config.py
=> Add Params to copy_config

Snakefile, scripts/prepare_gas_network.py
=> Add Params to prepare_gas_network

README.md
This PR include the license of datasets used into the repo.
=> License for Datasets
